# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{em-beanstalk}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan"]
  s.date = %q{2009-11-13}
  s.description = %q{EventMachine client for Beanstalkd}
  s.email = %q{dan@postrank.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYING",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/em-jack.rb",
     "lib/em-jack/beanstalk_connection.rb",
     "lib/em-jack/connection.rb",
     "lib/em-jack/errors.rb",
     "lib/em-jack/job.rb",
     "spec/connection_spec.rb",
     "spec/integration_spec.rb",
     "spec/job_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/em-jack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{EventMachine client for Beanstalkd}
  s.test_files = [
    "spec/connection_spec.rb",
     "spec/integration_spec.rb",
     "spec/job_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

